export const ROLE_SYNONYMS: Record<string, string[]> = {
  "Solutions Engineer": [
    "Solution Engineer",
    "SE",
    "Sr. SE",
    "Sales Engineer",
    "Pre-Sales Engineer",
    "Technical Solutions Engineer",
    "Solutions Eng",
    "Sol Eng",
  ],
  "Software Engineer": [
    "SWE",
    "Software Developer",
    "Developer",
    "Programmer",
    "Software Dev",
    "Eng",
    "SW Engineer",
    "Software Eng",
  ],
  "Senior Software Engineer": [
    "Sr. SWE",
    "Sr. Software Engineer",
    "Senior SWE",
    "Senior Developer",
    "Sr. Developer",
    "Sr Software Engineer",
    "Staff SWE",
  ],
  "Product Manager": ["PM", "Product Owner", "PO", "Product Lead", "Product Mgr", "Prod Manager"],
  "Data Scientist": [
    "Data Science",
    "DS",
    "ML Scientist",
    "Machine Learning Scientist",
    "Applied Scientist",
    "Research Scientist",
  ],
  "Machine Learning Engineer": [
    "ML Engineer",
    "MLE",
    "ML Eng",
    "AI Engineer",
    "Deep Learning Engineer",
  ],
  "Account Executive": [
    "AE",
    "Sales Rep",
    "Sales Representative",
    "Account Manager",
    "Sales Exec",
    "Enterprise AE",
  ],
  "Data Engineer": [
    "DE",
    "Data Eng",
    "Analytics Engineer",
    "ETL Developer",
    "Data Pipeline Engineer",
  ],
  "DevOps Engineer": [
    "DevOps",
    "SRE",
    "Site Reliability Engineer",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Cloud Engineer",
    "Systems Engineer",
  ],
  "UX Designer": [
    "User Experience Designer",
    "UX",
    "Product Designer",
    "UI/UX Designer",
    "Interaction Designer",
    "Experience Designer",
  ],
  "Engineering Manager": [
    "EM",
    "Eng Manager",
    "Engineering Lead",
    "Dev Manager",
    "Software Engineering Manager",
    "Tech Lead Manager",
  ],
  "VP of Engineering": [
    "VP Engineering",
    "VPE",
    "VP Eng",
    "Vice President Engineering",
    "Vice President of Engineering",
  ],
  CTO: [
    "Chief Technology Officer",
    "Chief Tech Officer",
    "VP Technology",
    "Head of Technology",
    "Head of Engineering",
  ],
  CFO: ["Chief Financial Officer", "VP Finance", "Head of Finance", "Finance Director"],
  COO: ["Chief Operating Officer", "VP Operations", "Head of Operations", "Operations Director"],
  CEO: ["Chief Executive Officer", "Founder", "Co-Founder", "Managing Director", "President"],
  "Business Analyst": ["BA", "Business Analysis", "Junior BA", "Associate BA", "Systems Analyst"],
  Consultant: [
    "Associate Consultant",
    "Junior Consultant",
    "Consulting Analyst",
    "Advisory Associate",
  ],
  "Management Consultant": [
    "Strategy Consultant",
    "MC",
    "Senior Consultant",
    "Principal Consultant",
    "Associate Consultant",
    "Engagement Manager",
  ],
  "Investment Banking Analyst": [
    "IB Analyst",
    "IBD Analyst",
    "Banking Analyst",
    "Investment Bank Analyst",
    "IB Associate",
  ],
  "Quantitative Analyst": [
    "Quant",
    "Quant Analyst",
    "Quantitative Researcher",
    "Quant Researcher",
    "Quantitative Developer",
  ],
  "Frontend Engineer": [
    "Front End Engineer",
    "Front-End Developer",
    "Frontend Developer",
    "UI Engineer",
    "Web Developer",
    "React Developer",
  ],
  "Backend Engineer": [
    "Back End Engineer",
    "Back-End Developer",
    "Backend Developer",
    "Server Engineer",
    "API Engineer",
  ],
  "Full Stack Engineer": [
    "Full-Stack Engineer",
    "Fullstack Engineer",
    "Full Stack Developer",
    "Fullstack Developer",
    "Full-Stack Developer",
  ],
  "Mobile Engineer": [
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "Mobile App Developer",
    "iOS Engineer",
    "Android Engineer",
  ],
  "Security Engineer": [
    "Security Analyst",
    "InfoSec Engineer",
    "Cybersecurity Engineer",
    "Application Security Engineer",
    "SecOps Engineer",
  ],
  "Technical Program Manager": ["TPM", "Tech Program Manager", "Technical PM", "Program Manager"],
  "Sales Development Representative": [
    "SDR",
    "BDR",
    "Business Development Representative",
    "Outbound Sales Rep",
    "Lead Development Rep",
  ],
  "Customer Success Manager": [
    "CSM",
    "Customer Success",
    "CS Manager",
    "Client Success Manager",
    "Customer Experience Manager",
  ],
  "Solutions Architect": [
    "SA",
    "Technical Architect",
    "Cloud Architect",
    "Enterprise Architect",
    "Integration Architect",
  ],
  "Technical Account Manager": ["TAM", "Tech Account Manager", "Technical Customer Manager"],
  "Product Marketing Manager": ["PMM", "Product Marketer", "Go-to-Market Manager", "GTM Manager"],
  "Growth Marketing Manager": [
    "Growth Manager",
    "Growth Lead",
    "Growth Hacker",
    "Growth Marketing",
  ],
  "Data Analyst": [
    "Data Analysis",
    "Junior Data Analyst",
    "Associate Data Analyst",
    "BI Analyst",
    "Business Intelligence Analyst",
  ],
  "QA Engineer": [
    "Quality Assurance Engineer",
    "Test Engineer",
    "SDET",
    "Software Development Engineer in Test",
    "QA",
    "Quality Engineer",
  ],
  Recruiter: [
    "Technical Recruiter",
    "Talent Acquisition",
    "Talent Acquisition Specialist",
    "Sourcer",
    "Recruiting Coordinator",
  ],
  "Private Equity Associate": [
    "PE Associate",
    "Private Equity Analyst",
    "PE Analyst",
    "Buyout Associate",
  ],
  "Venture Capital Associate": [
    "VC Associate",
    "Venture Associate",
    "VC Analyst",
    "Investment Associate",
  ],
  "Financial Analyst": [
    "Finance Analyst",
    "FP&A Analyst",
    "Corporate Finance Analyst",
    "Financial Planning Analyst",
  ],
  Trader: [
    "Equities Trader",
    "Fixed Income Trader",
    "Options Trader",
    "Derivatives Trader",
    "Prop Trader",
  ],
  "Portfolio Manager": ["PM (Finance)", "Fund Manager", "Asset Manager", "Investment Manager"],
  "Developer Advocate": [
    "DevRel",
    "Developer Relations",
    "Developer Evangelist",
    "Developer Relations Engineer",
    "Community Engineer",
  ],
  "Technical Writer": [
    "Tech Writer",
    "Documentation Engineer",
    "Docs Writer",
    "API Writer",
    "Content Developer",
  ],
  "Director of Engineering": [
    "Engineering Director",
    "Director Eng",
    "Dir of Engineering",
    "Senior Engineering Manager",
  ],
  "Director of Product": ["Product Director", "Director PM", "Dir of Product", "Head of Product"],
  "Director of Sales": [
    "Sales Director",
    "Director of Revenue",
    "Head of Sales",
    "Regional Sales Director",
  ],
  "HR Business Partner": ["HRBP", "People Partner", "People Business Partner", "HR Partner"],
  "Operations Manager": [
    "Ops Manager",
    "Business Operations Manager",
    "BizOps Manager",
    "Operations Lead",
  ],
  "Supply Chain Manager": ["SCM", "Logistics Manager", "Supply Chain Lead", "Procurement Manager"],
  "Compliance Officer": [
    "Compliance Manager",
    "Regulatory Compliance",
    "Compliance Analyst",
    "GRC Analyst",
  ],
  "Legal Counsel": [
    "Corporate Counsel",
    "In-House Counsel",
    "Associate General Counsel",
    "Attorney",
    "Lawyer",
  ],
};
